# This is (the relevant part of) the nginx configuration used to proxy requests
# for the moxfield deck source. The MOXFIELD_USER_AGENT below should be
# replaced with the user agent provided by Moxfield support for deployment.

http {
    # This declares a rate limiting zone named "reqzone" which limits each
    # remote host (identified by $binary_remote_addr which is IP) to 1 request
    # per second.
    limit_req_zone $binary_remote_addr zone=one:10m rate=1r/s;

    server {
        listen 80;
        server_name moxfield-proxy.feik.xyz;

        # This applies the rate limiting zone declared above to this server.
        # The burst=100 parameter allows users to make up to 100 requests
        # without rate limiting before the rate limit kicks in and they are
        # forced to wait 100 seconds before the next request. If those 100
        # requests are used up, users will receive a 503 error. delay=10 means
        # that those requests are processed immediately up to 10, instead of
        # one each second.
        #
        # source: https://blog.nginx.org/blog/rate-limiting-nginx
        limit_req zone=one burst=100 delay=10;

        location / {
            if ($http_user_agent !~* ".*architrice.*") {
                # Reject non-architrice users.
                return 400;
            }

            proxy_pass https://api.moxfield.com;
            proxy_set_header Host api.moxfield.com;
            proxy_set_header User-Agent "MoxKey; MOXFIELD_USER_AGENT";
            proxy_pass_request_headers on;
            proxy_ssl_server_name on;
        }
    }
}